using System;
using System.Collections.Generic;

namespace Soenneker.Holidays.Us;

public static partial class UsHolidays
{
    private static readonly IReadOnlyList<UsHolidayDefinition> _definitions = Array.AsReadOnly<UsHolidayDefinition>(
    [
        new(UsHolidayId.NewYearsDay, "New Year's Day", "January 1.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Fixed(y, 1, 1)),
        new(UsHolidayId.MartinLutherKingJrDay, "Martin Luther King Jr. Day", "Third Monday in January.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Nth(y, 1, DayOfWeek.Monday, 3)),
        new(UsHolidayId.WashingtonsBirthday, "Washington's Birthday / Presidents' Day", "Third Monday in February; state names vary.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Nth(y, 2, DayOfWeek.Monday, 3)),
        new(UsHolidayId.MemorialDay, "Memorial Day", "Last Monday in May.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Last(y, 5, DayOfWeek.Monday)),
        new(UsHolidayId.Juneteenth, "Juneteenth / Emancipation Day in Texas", "June 19. Calculation does not imply recognition before enactment.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US; TX", y => Fixed(y, 6, 19)),
        new(UsHolidayId.IndependenceDay, "Independence Day", "July 4.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Fixed(y, 7, 4)),
        new(UsHolidayId.LaborDay, "Labor Day", "First Monday in September.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Nth(y, 9, DayOfWeek.Monday, 1)),
        new(UsHolidayId.ColumbusDay, "Columbus Day", "Second Monday in October.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Nth(y, 10, DayOfWeek.Monday, 2)),
        new(UsHolidayId.VeteransDay, "Veterans Day", "November 11.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Fixed(y, 11, 11)),
        new(UsHolidayId.ThanksgivingDay, "Thanksgiving Day", "Fourth Thursday in November.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Nth(y, 11, DayOfWeek.Thursday, 4)),
        new(UsHolidayId.ChristmasDay, "Christmas Day", "December 25.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "US", y => Fixed(y, 12, 25)),
        new(UsHolidayId.InaugurationDay, "Presidential Inauguration Day", "January 20 every four years (year remainder 1). Federal recognition is limited to the designated Washington, D.C. area; Sunday substitution only.",
            "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/", "DC area", y => y % 4 == 1 ? Fixed(y, 1, 20) : []),
        new(UsHolidayId.MartinLutherKingJrBirthday, "Martin Luther King Jr. Birthday (January 15)", "January 15; distinct from the Monday observance.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL", y => Fixed(y, 1, 15)),
        new(UsHolidayId.RobertELeeBirthday, "Robert E. Lee Birthday (January 19)", "January 19.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL; KY", y => Fixed(y, 1, 19)),
        new(UsHolidayId.ConfederateHeroesDay, "Confederate Heroes Day", "January 19.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX", y => Fixed(y, 1, 19)),
        new(UsHolidayId.FranklinDRooseveltDay, "Franklin D. Roosevelt Day", "January 30.",
            "https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=46", "KY", y => Fixed(y, 1, 30)),
        new(UsHolidayId.LincolnsBirthday, "Lincoln's Birthday", "February 12.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA; FL; MO", y => Fixed(y, 2, 12)),
        new(UsHolidayId.SusanBAnthonyBirthday, "Susan B. Anthony Birthday", "February 15.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL", y => Fixed(y, 2, 15)),
        new(UsHolidayId.WashingtonsBirthdayFebruary22, "Washington's Birthday (February 22)", "February 22; actual birthday distinguished from third-Monday observance.",
            "https://www.leg.state.nv.us/nrs/NRS-236.html", "NV", y => Fixed(y, 2, 22)),
        new(UsHolidayId.MardiGras, "Mardi Gras / Shrove Tuesday", "47 days before Western Easter; recognition can be local or proclamation-dependent.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "LA; parts of FL", y => Easter(y, -47)),
        new(UsHolidayId.GoodFriday, "Good Friday", "Two days before Western Easter.",
            "https://www.legis.state.pa.us/WU01/LI/LI/US/PDF/1893/0/0138..PDF", "PA; FL; HI; TX (optional)", y => Easter(y, -2)),
        new(UsHolidayId.EasterSunday, "Easter Sunday", "Gregorian Western Easter; also a Sunday legal holiday in jurisdictions recognizing Sundays.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL", y => Easter(y, 0)),
        new(UsHolidayId.EasterMonday, "Easter Monday", "Day after Western Easter; supplemental calculation, not listed in the current North Carolina holiday statute.",
            "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_103/GS_103-4.html", "Supplemental Easter-relative date", y => Easter(y, 1)),
        new(UsHolidayId.CasimirPulaskiDay, "Casimir Pulaski Day", "First Monday in March.",
            "https://www.ilga.gov/ftp/ILCS/Ch%200005/Act%200490/000504900K15.html", "IL", y => Nth(y, 3, DayOfWeek.Monday, 1)),
        new(UsHolidayId.TownMeetingDay, "Town Meeting Day", "First Tuesday in March; local meetings may be scheduled differently.",
            "https://legislature.vermont.gov/statutes/section/01/007/00371", "VT", y => Nth(y, 3, DayOfWeek.Tuesday, 1)),
        new(UsHolidayId.TexasIndependenceDay, "Texas Independence Day", "March 2.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX", y => Fixed(y, 3, 2)),
        new(UsHolidayId.EvacuationDay, "Evacuation Day", "March 17; Suffolk County, Massachusetts, with statutory limitations.",
            "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleI/Chapter4/Section7", "MA (Suffolk County)", y => Fixed(y, 3, 17)),
        new(UsHolidayId.PrinceKuhioDay, "Prince Jonah Kuhio Kalanianaole Day", "March 26.",
            "https://dhrd.hawaii.gov/state-observed-holidays/", "HI", y => Fixed(y, 3, 26)),
        new(UsHolidayId.SewardsDay, "Seward's Day", "Last Monday in March.",
            "https://www.akleg.gov/statutesPDF/Title-44.pdf", "AK", y => Last(y, 3, DayOfWeek.Monday)),
        new(UsHolidayId.CesarChavezDay, "Cesar Chavez Day / Farmworkers Day", "March 31; naming and applicability vary.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA; TX (optional)", y => Fixed(y, 3, 31)),
        new(UsHolidayId.TuskegeeAirmenCommemorationDay, "Tuskegee Airmen Commemoration Day", "Fourth Thursday in March.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL", y => Nth(y, 3, DayOfWeek.Thursday, 4)),
        new(UsHolidayId.PascuaFloridaDay, "Pascua Florida Day", "April 2; statutory date, not a separately shifted ceremonial observance.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL", y => Fixed(y, 4, 2)),
        new(UsHolidayId.DcEmancipationDay, "District of Columbia Emancipation Day", "April 16.",
            "https://code.dccouncil.gov/us/dc/council/code/sections/1-612.02", "DC", y => Fixed(y, 4, 16)),
        new(UsHolidayId.PatriotsDay, "Patriots' Day", "Third Monday in April.",
            "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleI/Chapter4/Section7", "MA; ME", y => Nth(y, 4, DayOfWeek.Monday, 3)),
        new(UsHolidayId.SanJacintoDay, "San Jacinto Day", "April 21.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX", y => Fixed(y, 4, 21)),
        new(UsHolidayId.GenocideRemembranceDay, "Genocide Remembrance Day", "April 24.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA", y => Fixed(y, 4, 24)),
        new(UsHolidayId.ConfederateMemorialDayApril26, "Confederate Memorial Day (April 26)", "April 26; distinct from Monday and May/June variants.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL", y => Fixed(y, 4, 26)),
        new(UsHolidayId.ConfederateMemorialDayFourthMonday, "Confederate Memorial Day (fourth Monday in April)", "Fourth Monday in April.",
            "https://personnel.alabama.gov/Downloads/StateHolidays.pdf", "AL", y => Nth(y, 4, DayOfWeek.Monday, 4)),
        new(UsHolidayId.ArborDay, "Arbor Day (Nebraska)", "Last Friday in April; other states have different ceremonial Arbor Days.",
            "https://nebraskalegislature.gov/laws/statutes.php?statute=s2522021000", "NE", y => Last(y, 4, DayOfWeek.Friday)),
        new(UsHolidayId.RhodeIslandIndependenceDay, "Rhode Island Independence Day", "May 4.",
            "https://webserver.rilegislature.gov/Statutes/TITLE25/25-1/25-1-1_25-1-1.htm", "RI", y => Fixed(y, 5, 4)),
        new(UsHolidayId.TrumanDay, "Truman Day", "May 8.",
            "https://www.revisor.mo.gov/main/OneSection.aspx?section=9.010", "MO", y => Fixed(y, 5, 8)),
        new(UsHolidayId.ConfederateMemorialDayMay10, "Confederate Memorial Day (May 10)", "May 10.",
            "https://www.scstatehouse.gov/code/t53c005.php", "SC", y => Fixed(y, 5, 10)),
        new(UsHolidayId.JeffersonDavisBirthday, "Jefferson Davis Birthday / Confederate Memorial Day (June 3)", "June 3.",
            "https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=46", "KY; FL", y => Fixed(y, 6, 3)),
        new(UsHolidayId.JeffersonDavisBirthdayFirstMonday, "Jefferson Davis Birthday (first Monday in June)", "First Monday in June.",
            "https://personnel.alabama.gov/Downloads/StateHolidays.pdf", "AL", y => Nth(y, 6, DayOfWeek.Monday, 1)),
        new(UsHolidayId.KingKamehamehaDay, "King Kamehameha I Day", "June 11.",
            "https://dhrd.hawaii.gov/state-observed-holidays/", "HI", y => Fixed(y, 6, 11)),
        new(UsHolidayId.FlagDay, "Flag Day", "June 14.",
            "https://www.legis.state.pa.us/WU01/LI/LI/US/PDF/1893/0/0138..PDF", "PA; FL", y => Fixed(y, 6, 14)),
        new(UsHolidayId.BunkerHillDay, "Bunker Hill Day", "June 17; Suffolk County, Massachusetts, with statutory limitations.",
            "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleI/Chapter4/Section7", "MA (Suffolk County)", y => Fixed(y, 6, 17)),
        new(UsHolidayId.WestVirginiaDay, "West Virginia Day", "June 20.",
            "https://code.wvlegislature.gov/2-2-1/", "WV", y => Fixed(y, 6, 20)),
        new(UsHolidayId.PioneerDay, "Pioneer Day", "July 24.",
            "https://le.utah.gov/xcode/Title63G/Chapter1/C63G-1-S301.html", "UT", y => Fixed(y, 7, 24)),
        new(UsHolidayId.VictoryDay, "Victory Day", "Second Monday in August.",
            "https://webserver.rilegislature.gov/Statutes/TITLE25/25-1/25-1-1_25-1-1.htm", "RI", y => Nth(y, 8, DayOfWeek.Monday, 2)),
        new(UsHolidayId.BenningtonBattleDay, "Bennington Battle Day", "August 16.",
            "https://legislature.vermont.gov/statutes/section/01/007/00371", "VT", y => Fixed(y, 8, 16)),
        new(UsHolidayId.HawaiiStatehoodDay, "Hawaii Statehood Day", "Third Friday in August.",
            "https://dhrd.hawaii.gov/state-observed-holidays/", "HI", y => Nth(y, 8, DayOfWeek.Friday, 3)),
        new(UsHolidayId.LyndonBainesJohnsonDay, "Lyndon Baines Johnson Day", "August 27.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX", y => Fixed(y, 8, 27)),
        new(UsHolidayId.HueyPLongDay, "Huey P. Long Day", "August 30; agency observance may depend on proclamation.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "LA", y => Fixed(y, 8, 30)),
        new(UsHolidayId.CaliforniaAdmissionDay, "California Admission Day", "September 9.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA", y => Fixed(y, 9, 9)),
        new(UsHolidayId.NativeAmericanDay, "Native American Day (California)", "Fourth Friday in September.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA", y => Nth(y, 9, DayOfWeek.Friday, 4)),
        new(UsHolidayId.FrancesXavierCabriniDay, "Frances Xavier Cabrini Day", "First Monday in October.",
            "https://www.leg.colorado.gov/bills/HB20-1031", "CO", y => Nth(y, 10, DayOfWeek.Monday, 1)),
        new(UsHolidayId.IndigenousPeoplesDay, "Indigenous Peoples' Day", "Second Monday in October; also called Native Americans' Day in South Dakota.",
            "https://nebraskalegislature.gov/laws/statutes.php?statute=s2522021000", "NE; ME; SD", y => Nth(y, 10, DayOfWeek.Monday, 2)),
        new(UsHolidayId.AlaskaDay, "Alaska Day", "October 18.",
            "https://www.akleg.gov/statutesPDF/Title-44.pdf", "AK", y => Fixed(y, 10, 18)),
        new(UsHolidayId.NevadaDay, "Nevada Day (last Friday in October)", "Last Friday in October; use this rule for the statutory observance.",
            "https://www.leg.state.nv.us/nrs/NRS-236.html", "NV", y => Last(y, 10, DayOfWeek.Friday)),
        new(UsHolidayId.NevadaAdmissionAnniversary, "Nevada admission anniversary (October 31)", "October 31; the statutory observance is NevadaDay.",
            "https://www.leg.state.nv.us/nrs/NRS-236.html", "NV", y => Fixed(y, 10, 31)),
        new(UsHolidayId.AllSaintsDay, "All Saints' Day", "November 1.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "LA", y => Fixed(y, 11, 1)),
        new(UsHolidayId.ElectionDay, "November Election Day (annual)", "Tuesday after the first Monday in November, every year; excludes primaries and special elections.",
            "https://www.legis.state.pa.us/WU01/LI/LI/US/PDF/1893/0/0138..PDF", "PA", y => Offset(Nth(y, 11, DayOfWeek.Monday, 1), 1)),
        new(UsHolidayId.GeneralElectionDay, "General Election Day (even years)", "Tuesday after the first Monday in November in even years.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "LA; HI; RI", y => y % 2 == 0 ? Offset(Nth(y, 11, DayOfWeek.Monday, 1), 1) : []),
        new(UsHolidayId.DayAfterThanksgiving, "Day after Thanksgiving / Family Day", "Friday after Thanksgiving.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX; NV; NE; SC", y => Offset(Nth(y, 11, DayOfWeek.Thursday, 4), 1)),
        new(UsHolidayId.AmericanIndianHeritageDay, "American Indian Heritage Day", "Friday after Thanksgiving.",
            "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=ggp&enactments=false&section=1-111", "MD", y => Offset(Nth(y, 11, DayOfWeek.Thursday, 4), 1)),
        new(UsHolidayId.ChristmasEve, "Christmas Eve", "December 24; some jurisdictions recognize only a partial day.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX; SC", y => Fixed(y, 12, 24)),
        new(UsHolidayId.DayAfterChristmas, "Day after Christmas", "December 26.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX; SC", y => Fixed(y, 12, 26)),
        new(UsHolidayId.NewYearsEve, "New Year's Eve", "December 31; recognition may be limited to courts or government employees.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "LA (courts)", y => Fixed(y, 12, 31)),
        new(UsHolidayId.BattleOfNewOrleans, "Battle of New Orleans", "January 8.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "LA", y => Fixed(y, 1, 8)),
        new(UsHolidayId.RoshHashanah, "Rosh Hashanah", "Tishri 1 and 2; civil daytime dates, not the preceding sunset.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX (optional)", y => Hebrew(y, 1, 1, 2), minimumYear: 1583, maximumYear: 2238),
        new(UsHolidayId.YomKippur, "Yom Kippur", "Tishri 10; civil daytime date, not the preceding sunset.",
            "https://tcss.legis.texas.gov/resources/GV/htm/GV.662.htm", "TX (optional)", y => Hebrew(y, 1, 10, 1), minimumYear: 1583, maximumYear: 2238),
        new(UsHolidayId.LunarNewYear, "Lunar New Year", "Chinese lunisolar new year using the .NET calendar; civil date.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA", y => LunarNewYear(y), minimumYear: 1901, maximumYear: 2100),
        new(UsHolidayId.Sunday, "Sunday", "Every Sunday; include only where relevant to the caller's policy.",
            "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0683/Sections/0683.01.html", "FL; CA; LA", y => Weekly(y, DayOfWeek.Sunday)),
        new(UsHolidayId.SaturdayHalfHoliday, "Saturday half-holiday", "Every Saturday from noon through the end of the day; context-specific.",
            "https://www.legis.state.pa.us/WU01/LI/LI/US/PDF/1893/0/0138..PDF", "PA", y => Weekly(y, DayOfWeek.Saturday), startTime: new TimeOnly(12, 0)),
        new(UsHolidayId.SaturdayHoliday, "Saturday holiday", "Every Saturday; limited to specified localities and institutions.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "Parts of LA", y => Weekly(y, DayOfWeek.Saturday)),
        new(UsHolidayId.WednesdayHalfHoliday, "Wednesday half-holiday", "Every Wednesday from noon; limited to specified Louisiana banking institutions.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "Parts of LA", y => Weekly(y, DayOfWeek.Wednesday), startTime: new TimeOnly(12, 0)),
        new(UsHolidayId.CaliforniaGoodFridayPartial, "Good Friday (California partial day)", "Good Friday from noon until 3 p.m.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA", y => Easter(y, -2), startTime: new TimeOnly(12, 0), endTime: new TimeOnly(15, 0)),
        new(UsHolidayId.Diwali, "Diwali", "Requires an authoritative Hindu-calendar date; no approximate lunar calculation is substituted.",
            "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=6700.", "CA", null),
        new(UsHolidayId.ProclaimedHoliday, "Proclaimed or special holiday", "Dates declared by a President, governor, or local authority must be supplied externally.",
            "https://legis.la.gov/legis/Law.aspx?d=74097", "US; states and localities", null),
        new(UsHolidayId.MarylandDay, "Maryland Day", "March 25.",
            "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=ggp&enactments=false&section=1-111", "MD", y => Fixed(y, 3, 25)),
        new(UsHolidayId.DefendersDay, "Defenders' Day", "September 12.",
            "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=ggp&enactments=false&section=1-111", "MD", y => Fixed(y, 9, 12)),
        new(UsHolidayId.GreekIndependenceDay, "Greek Independence Day", "March 25.",
            "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_103/GS_103-4.html", "NC", y => Fixed(y, 3, 25)),
        new(UsHolidayId.HalifaxResolvesDay, "Anniversary of the Halifax Resolves", "April 12.",
            "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_103/GS_103-4.html", "NC", y => Fixed(y, 4, 12)),
        new(UsHolidayId.MecklenburgDeclarationDay, "Mecklenburg Declaration of Independence anniversary", "May 20.",
            "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_103/GS_103-4.html", "NC", y => Fixed(y, 5, 20)),
        new(UsHolidayId.FirstRespondersDay, "First Responders Day", "September 11.",
            "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_103/GS_103-4.html", "NC", y => Fixed(y, 9, 11)),
        new(UsHolidayId.ConfederateMemorialDayLastMonday, "Confederate Memorial Day (last Monday in April)", "Last Monday in April; differs from the fourth Monday in some years.",
            "https://sos.ms.gov/communications-publications/state-holidays", "MS", y => Last(y, 4, DayOfWeek.Monday)),
        new(UsHolidayId.JuneteenthThirdFriday, "Juneteenth (third Friday in June)", "Third Friday in June; distinct from the June 19 rule.",
            "https://www.nj.gov/dcf/documents/news/Juneteenth%20Holiday.pdf", "NJ", y => Nth(y, 6, DayOfWeek.Friday, 3)),
        new(UsHolidayId.RosaParksDay, "Rosa Parks Day", "December 1; Alabama's published calendar labels this commemoration only, not an automatic closure.",
            "https://personnel.alabama.gov/Downloads/StateHolidays.pdf", "AL (commemoration)", y => Fixed(y, 12, 1)),
        new(UsHolidayId.UtahJuneteenth, "Juneteenth (Utah Monday rule)",
            "June 19 when Monday; preceding Monday when Tuesday through Friday; following Monday when Saturday or Sunday.",
            "https://www.utcourts.gov/en/about/miscellaneous/law-library/holidays.html", "UT", y => UtahJuneteenth(y)),
        new(UsHolidayId.MothersDay, "Mother's Day", "Second Sunday in May.",
            "https://www.azleg.gov/ars/1/00301.htm", "AZ", y => Nth(y, 5, DayOfWeek.Sunday, 2)),
        new(UsHolidayId.FathersDay, "Father's Day", "Third Sunday in June.",
            "https://www.azleg.gov/ars/1/00301.htm", "AZ", y => Nth(y, 6, DayOfWeek.Sunday, 3)),
        new(UsHolidayId.AmericanFamilyDay, "American Family Day", "First Sunday in August.",
            "https://www.azleg.gov/ars/1/00301.htm", "AZ", y => Nth(y, 8, DayOfWeek.Sunday, 1)),
        new(UsHolidayId.ArizonaNativeAmericanDay, "Native American Day (Arizona)", "June 2; ceremonial observance on the following Sunday when not Sunday.",
            "https://www.azleg.gov/ars/1/00301.htm", "AZ", y => Fixed(y, 6, 2)),
        new(UsHolidayId.NavajoCodeTalkersDay, "National Navajo Code Talkers Day", "August 14; ceremonial observance on the following Sunday when not Sunday.",
            "https://www.azleg.gov/ars/1/00301.htm", "AZ", y => Fixed(y, 8, 14)),
        new(UsHolidayId.ConstitutionCommemorationDay, "Constitution Commemoration Day", "September 17; ceremonial observance on the preceding Sunday when not Sunday.",
            "https://www.azleg.gov/ars/1/00301.htm", "AZ", y => Fixed(y, 9, 17)),
        new(UsHolidayId.NewYorkFlagDay, "Flag Day (New York)", "Second Sunday in June; distinct from June 14.",
            "https://www.nysenate.gov/legislation/laws/GCN/24", "NY", y => Nth(y, 6, DayOfWeek.Sunday, 2)),
        new(UsHolidayId.WisconsinGoodFridayPartial, "Good Friday (Wisconsin worship period)", "Good Friday from 11 a.m. until 3 p.m.",
            "https://docs.legis.wisconsin.gov/statutes/statutes/995/20", "WI", y => Easter(y, -2), startTime: new TimeOnly(11, 0), endTime: new TimeOnly(15, 0)),
        new(UsHolidayId.WisconsinPartisanPrimaryDay, "Wisconsin partisan primary", "Second Tuesday in August in even years; excludes special or rescheduled elections.",
            "https://docs.legis.wisconsin.gov/statutes/statutes/5/02/12s", "WI", y => y % 2 == 0 ? Nth(y, 8, DayOfWeek.Tuesday, 2) : []),
        new(UsHolidayId.WestVirginiaPrimaryDay, "West Virginia primary election", "Second Tuesday in May in even years; excludes special or rescheduled elections.",
            "https://code.wvlegislature.gov/3-5-1/", "WV", y => y % 2 == 0 ? Nth(y, 5, DayOfWeek.Tuesday, 2) : []),
        new(UsHolidayId.IndianaPrimaryDay, "Indiana regular primary election", "Tuesday after the first Monday in May, even years and municipal election years (remainder 3).",
            "https://iga.in.gov/laws/current/ic/titles/3#3-10-1-1", "IN", y => y % 4 != 1 ? Offset(Nth(y, 5, DayOfWeek.Monday, 1), 1) : []),
        new(UsHolidayId.IndianaElectionDay, "Indiana regular November election", "Tuesday after the first Monday in November, even years and municipal election years (remainder 3).",
            "https://iga.in.gov/laws/current/ic/titles/3#3-10", "IN", y => y % 4 != 1 ? Offset(Nth(y, 11, DayOfWeek.Monday, 1), 1) : []),
        new(UsHolidayId.DelawareReturnDay, "Return Day (Sussex County)", "Thursday after the biennial November election, from noon.",
            "https://delcode.delaware.gov/title1/c005/", "DE (Sussex County)", y => y % 2 == 0 ? Offset(Nth(y, 11, DayOfWeek.Monday, 1), 3) : [], startTime: new TimeOnly(12, 0)),
        new(UsHolidayId.JuneteenthThirdSaturday, "Juneteenth (Louisiana statutory date)", "Third Saturday in June; state employee June 19 closures are separately proclaimed.",
            "https://www.legis.la.gov/legis/Law.aspx?d=1238710", "LA", y => Nth(y, 6, DayOfWeek.Saturday, 3)),
        new(UsHolidayId.NorthDakotaChristmasEvePartial, "Christmas Eve (North Dakota offices)", "December 24 from noon, unless a weekend or the substituted Christmas holiday.",
            "https://ndlegis.gov/prod/cencode/t01c03.pdf", "ND (state offices)", y => new DateOnly(y, 12, 24).DayOfWeek is DayOfWeek.Friday or DayOfWeek.Saturday or DayOfWeek.Sunday ? [] : Fixed(y, 12, 24), startTime: new TimeOnly(12, 0)),
        new(UsHolidayId.OklahomaAdditionalChristmasHoliday, "Additional Oklahoma Christmas holiday", "Requires the executive order selecting the additional Christmas date; do not assume December 24.",
            "https://oklahoma.gov/omes/divisions/human-capital-management/employee-benefits/leave-holidays/holidays.html", "OK", null),
        new(UsHolidayId.AdditionalElectionDay, "Additional or special election holiday", "Supply applicable special, municipal, primary, or rescheduled election dates from the election authority.",
            "https://iga.in.gov/laws/current/ic/titles/1#1-1-9", "IN; WV; WI (conditional)", null),
    ]);
}

